name: zoomer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^7.0.1

  #https://pub.dev/packages/equatable
  equatable: ^2.0.0

  #https://pub.dev/packages/hive
  hive: ^2.0.4

  #https://pub.dev/packages/flutter_secure_storage
  flutter_secure_storage: ^4.2.0

  #https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.0.5

  #https://pub.dev/packages/dartz
  dartz: ^0.9.2

  #https://pub.dev/packages/data_connection_checker
  data_connection_checker: ^0.3.4

  #https://pub.dev/packages/dio
  dio: ^4.0.0

  #https://pub.dev/packages/retrofit
  retrofit: ^2.0.0

  #https://pub.dev/packages/json_annotation
  json_annotation: ^4.0.1

  #https://pub.dev/packages/formz
  formz: ^0.4.0

  #https://pub.dev/packages/flutter_svg
  flutter_svg: ^0.22.0

  #https://pub.dev/packages/get_it
  get_it: ^7.1.3

  #https://pub.dev/packages/intlhttps://pub.dev/packages/libphonenumber_plugin
  intl: ^0.17.0

  #https://pub.dev/packages/libphonenumber_plugin
  libphonenumber_plugin: ^0.2.3

  #https://pub.dev/packages/freezed
  freezed: ^0.14.2

  #https://pub.dev/packages/modal_bottom_sheet
  modal_bottom_sheet: ^2.0.0

  #https://pub.dev/packages/flutter_keyboard_visibility
  keyboard_visibility: ^0.5.6

  #https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.0.0

  #https://pub.dev/packages/flutter_native_timezone
  flutter_native_timezone: ^1.1.0

  #https://pub.dev/packages/flutter_multi_formatter
  flutter_multi_formatter: ^2.1.0

  #https://pub.dev/packages/easy_mask
  easy_mask: ^1.1.5

  #https://pub.dev/packages/flutter_styled_toast
  flutter_styled_toast: ^2.0.0

  #https://pub.dev/packages/country_code_picker
  country_code_picker: ^2.0.1

  #https://pub.dev/packages/country_picker
  country_picker: ^2.0.5

  #https://pub.dev/packages/country_pickers
  country_pickers: ^2.0.0

  #https://pub.dev/packages/google_maps_flutter
  google_maps_flutter: ^2.0.8

  flutter_masked_text: ^0.8.0

  #https://pub.dev/packages/mask_text_input_formatter
  mask_text_input_formatter: ^2.0.0

  #https://pub.dev/packages/edit_distance
  edit_distance: ^0.4.1

  #https://pub.dev/packages/tuple
  tuple: ^2.0.0

  #https://pub.dev/packages/flutter_money_formatter
  flutter_money_formatter:
    git:
      url: git://github.com/anisalibegic/flutter_money_formatter.git

  #https://pub.dev/packages/pinput
  pinput: ^1.2.0

  html: 0.14.0+3
  flutter_webrtc: ^0.2.8
  #https://pub.dev/packages/webview_flutter
  webview_flutter: ^2.0.12

  flutter_overlay_loader: ^1.0.3

  permission_handler: ^8.1.6

  rxdart: ^0.27.2

  #https://pub.dev/packages/pausable_timer
  pausable_timer: ^1.0.0+1

  #https://pub.dev/packages/firebase_messaging
  firebase_messaging: ^10.0.7

  firebase_core: ^1.2.0

  overlay_support: ^1.2.1

dev_dependencies:
  retrofit_generator: ^2.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.0.3
  flutter_gen_runner: ^3.0.1
  json_serializable: ^4.1.2
  analyzer: ^1.5.0
  flutter_launcher_icons: ^0.9.0
  change_app_package_name: ^0.1.3
  flutter_native_splash: ^1.2.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  assets:
    - assets/images/
    - assets/i18n/

